version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export MY_ENV_VAR="${ENVVAR}"' >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV

      - run:
          name: Greeting
          command: echo {{ $MY_ENV_VAR:-env}}.enc is here.

      - run:
          name: Print the Current Time
          command: date
