version: 2
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: echo $ENVVAR
  test:
    docker:
      - image: circleci/nodejs:8.1.2
    steps:
      - checkout
      - run: $ENVVAR
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
